// 全国沿海城市与附近导航点。坐标用于城市筛选和附近导航，不代表精确下滩入口。
const nationalCities = [
  {
    "id": "dalian",
    "name": "大连",
    "province": "辽宁",
    "latitude": 38.92,
    "longitude": 121.62,
    "scale": 8
  },
  {
    "id": "dandong",
    "name": "丹东",
    "province": "辽宁",
    "latitude": 39.88,
    "longitude": 124.35,
    "scale": 8
  },
  {
    "id": "yingkou",
    "name": "营口",
    "province": "辽宁",
    "latitude": 40.67,
    "longitude": 122.23,
    "scale": 8
  },
  {
    "id": "panjin",
    "name": "盘锦",
    "province": "辽宁",
    "latitude": 41.12,
    "longitude": 122.07,
    "scale": 8
  },
  {
    "id": "jinzhou",
    "name": "锦州",
    "province": "辽宁",
    "latitude": 41.1,
    "longitude": 121.13,
    "scale": 8
  },
  {
    "id": "huludao",
    "name": "葫芦岛",
    "province": "辽宁",
    "latitude": 40.72,
    "longitude": 120.84,
    "scale": 8
  },
  {
    "id": "qinhuangdao",
    "name": "秦皇岛",
    "province": "河北",
    "latitude": 39.94,
    "longitude": 119.6,
    "scale": 8
  },
  {
    "id": "tangshan",
    "name": "唐山",
    "province": "河北",
    "latitude": 39.2,
    "longitude": 118.7,
    "scale": 8
  },
  {
    "id": "cangzhou",
    "name": "沧州",
    "province": "河北",
    "latitude": 38.3,
    "longitude": 117.8,
    "scale": 8
  },
  {
    "id": "tianjin",
    "name": "天津",
    "province": "天津",
    "latitude": 39.02,
    "longitude": 117.72,
    "scale": 8
  },
  {
    "id": "lianyungang",
    "name": "连云港",
    "province": "江苏",
    "latitude": 34.6,
    "longitude": 119.22,
    "scale": 8
  },
  {
    "id": "yancheng",
    "name": "盐城",
    "province": "江苏",
    "latitude": 33.4,
    "longitude": 120.2,
    "scale": 7
  },
  {
    "id": "nantong",
    "name": "南通",
    "province": "江苏",
    "latitude": 32,
    "longitude": 121.1,
    "scale": 7
  },
  {
    "id": "shanghai",
    "name": "上海",
    "province": "上海",
    "latitude": 31.1,
    "longitude": 121.7,
    "scale": 8
  },
  {
    "id": "jiaxing",
    "name": "嘉兴",
    "province": "浙江",
    "latitude": 30.63,
    "longitude": 121.1,
    "scale": 8
  },
  {
    "id": "ningbo",
    "name": "宁波",
    "province": "浙江",
    "latitude": 29.65,
    "longitude": 121.75,
    "scale": 8
  },
  {
    "id": "zhoushan",
    "name": "舟山",
    "province": "浙江",
    "latitude": 30,
    "longitude": 122.2,
    "scale": 8
  },
  {
    "id": "taizhou-zj",
    "name": "台州",
    "province": "浙江",
    "latitude": 28.65,
    "longitude": 121.45,
    "scale": 8
  },
  {
    "id": "wenzhou",
    "name": "温州",
    "province": "浙江",
    "latitude": 27.9,
    "longitude": 120.85,
    "scale": 8
  },
  {
    "id": "ningde",
    "name": "宁德",
    "province": "福建",
    "latitude": 26.7,
    "longitude": 119.85,
    "scale": 8
  },
  {
    "id": "fuzhou",
    "name": "福州",
    "province": "福建",
    "latitude": 25.9,
    "longitude": 119.55,
    "scale": 8
  },
  {
    "id": "putian",
    "name": "莆田",
    "province": "福建",
    "latitude": 25.3,
    "longitude": 119.1,
    "scale": 8
  },
  {
    "id": "quanzhou",
    "name": "泉州",
    "province": "福建",
    "latitude": 24.85,
    "longitude": 118.65,
    "scale": 8
  },
  {
    "id": "xiamen",
    "name": "厦门",
    "province": "福建",
    "latitude": 24.48,
    "longitude": 118.12,
    "scale": 9
  },
  {
    "id": "zhangzhou",
    "name": "漳州",
    "province": "福建",
    "latitude": 24.05,
    "longitude": 117.65,
    "scale": 8
  },
  {
    "id": "chaozhou",
    "name": "潮州",
    "province": "广东",
    "latitude": 23.6,
    "longitude": 116.95,
    "scale": 8
  },
  {
    "id": "shantou",
    "name": "汕头",
    "province": "广东",
    "latitude": 23.35,
    "longitude": 116.75,
    "scale": 8
  },
  {
    "id": "jieyang",
    "name": "揭阳",
    "province": "广东",
    "latitude": 23.05,
    "longitude": 116.35,
    "scale": 8
  },
  {
    "id": "shanwei",
    "name": "汕尾",
    "province": "广东",
    "latitude": 22.78,
    "longitude": 115.35,
    "scale": 8
  },
  {
    "id": "huizhou",
    "name": "惠州",
    "province": "广东",
    "latitude": 22.75,
    "longitude": 114.75,
    "scale": 8
  },
  {
    "id": "shenzhen",
    "name": "深圳",
    "province": "广东",
    "latitude": 22.55,
    "longitude": 114.25,
    "scale": 9
  },
  {
    "id": "dongguan",
    "name": "东莞",
    "province": "广东",
    "latitude": 22.8,
    "longitude": 113.7,
    "scale": 8
  },
  {
    "id": "guangzhou",
    "name": "广州",
    "province": "广东",
    "latitude": 22.85,
    "longitude": 113.55,
    "scale": 8
  },
  {
    "id": "zhongshan",
    "name": "中山",
    "province": "广东",
    "latitude": 22.48,
    "longitude": 113.48,
    "scale": 8
  },
  {
    "id": "zhuhai",
    "name": "珠海",
    "province": "广东",
    "latitude": 22.25,
    "longitude": 113.55,
    "scale": 8
  },
  {
    "id": "jiangmen",
    "name": "江门",
    "province": "广东",
    "latitude": 22.1,
    "longitude": 112.8,
    "scale": 7
  },
  {
    "id": "yangjiang",
    "name": "阳江",
    "province": "广东",
    "latitude": 21.75,
    "longitude": 111.75,
    "scale": 8
  },
  {
    "id": "maoming",
    "name": "茂名",
    "province": "广东",
    "latitude": 21.55,
    "longitude": 110.95,
    "scale": 8
  },
  {
    "id": "zhanjiang",
    "name": "湛江",
    "province": "广东",
    "latitude": 21.2,
    "longitude": 110.35,
    "scale": 8
  },
  {
    "id": "beihai",
    "name": "北海",
    "province": "广西",
    "latitude": 21.48,
    "longitude": 109.15,
    "scale": 9
  },
  {
    "id": "qinzhou",
    "name": "钦州",
    "province": "广西",
    "latitude": 21.75,
    "longitude": 108.65,
    "scale": 8
  },
  {
    "id": "fangchenggang",
    "name": "防城港",
    "province": "广西",
    "latitude": 21.65,
    "longitude": 108.2,
    "scale": 8
  },
  {
    "id": "haikou",
    "name": "海口",
    "province": "海南",
    "latitude": 20.02,
    "longitude": 110.25,
    "scale": 9
  },
  {
    "id": "wenchang",
    "name": "文昌",
    "province": "海南",
    "latitude": 19.62,
    "longitude": 110.85,
    "scale": 8
  },
  {
    "id": "qionghai",
    "name": "琼海",
    "province": "海南",
    "latitude": 19.22,
    "longitude": 110.58,
    "scale": 8
  },
  {
    "id": "wanning",
    "name": "万宁",
    "province": "海南",
    "latitude": 18.75,
    "longitude": 110.28,
    "scale": 8
  },
  {
    "id": "lingshui",
    "name": "陵水",
    "province": "海南",
    "latitude": 18.45,
    "longitude": 109.95,
    "scale": 8
  },
  {
    "id": "sanya",
    "name": "三亚",
    "province": "海南",
    "latitude": 18.25,
    "longitude": 109.55,
    "scale": 9
  },
  {
    "id": "ledong",
    "name": "乐东",
    "province": "海南",
    "latitude": 18.65,
    "longitude": 108.85,
    "scale": 8
  },
  {
    "id": "dongfang",
    "name": "东方",
    "province": "海南",
    "latitude": 19.1,
    "longitude": 108.65,
    "scale": 8
  },
  {
    "id": "danzhou",
    "name": "儋州",
    "province": "海南",
    "latitude": 19.55,
    "longitude": 109.2,
    "scale": 8
  },
  {
    "id": "lingao",
    "name": "临高",
    "province": "海南",
    "latitude": 19.9,
    "longitude": 109.7,
    "scale": 8
  },
  {
    "id": "chengmai",
    "name": "澄迈",
    "province": "海南",
    "latitude": 19.92,
    "longitude": 110,
    "scale": 8
  }
]

const nationalSpots = [
  {
    "id": "dalian-fujiazhuang",
    "cityId": "dalian",
    "cityName": "大连",
    "name": "傅家庄海滨浴场（附近）",
    "area": "西岗区",
    "latitude": 38.866,
    "longitude": 121.614,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "dalian-xiajiahezi",
    "cityId": "dalian",
    "cityName": "大连",
    "name": "夏家河子海滨公园（附近）",
    "area": "甘井子区",
    "latitude": 39.009,
    "longitude": 121.546,
    "type": "沙滩",
    "harvest": "蛤蜊 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "dalian-jinshitan",
    "cityId": "dalian",
    "cityName": "大连",
    "name": "金石滩黄金海岸（附近）",
    "area": "金普新区",
    "latitude": 39.083,
    "longitude": 122.008,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "dandong-zhangdao",
    "cityId": "dandong",
    "cityName": "丹东",
    "name": "獐岛海滨岸段（附近）",
    "area": "东港市",
    "latitude": 39.759,
    "longitude": 123.596,
    "type": "礁石 + 沙滩",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 14,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "dandong-daludao",
    "cityId": "dandong",
    "cityName": "丹东",
    "name": "大鹿岛海滨浴场（附近）",
    "area": "东港市",
    "latitude": 39.752,
    "longitude": 123.745,
    "type": "沙滩",
    "harvest": "蛤蜊 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "yingkou-shanhai",
    "cityId": "yingkou",
    "cityName": "营口",
    "name": "山海广场海滩（附近）",
    "area": "鲅鱼圈区",
    "latitude": 40.219,
    "longitude": 122.118,
    "type": "沙滩",
    "harvest": "蛤蜊 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "yingkou-baishawan",
    "cityId": "yingkou",
    "cityName": "营口",
    "name": "白沙湾黄金海岸（附近）",
    "area": "盖州市",
    "latitude": 40.006,
    "longitude": 122.108,
    "type": "沙滩",
    "harvest": "蛤蜊 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "panjin-redbeach",
    "cityId": "panjin",
    "cityName": "盘锦",
    "name": "红海滩国家风景廊道（附近）",
    "area": "大洼区",
    "latitude": 40.893,
    "longitude": 121.999,
    "type": "滨海湿地",
    "harvest": "仅观察，不采集",
    "terrainSafety": 8,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "panjin-liaodongbay",
    "cityId": "panjin",
    "cityName": "盘锦",
    "name": "辽东湾新区滨海岸段（附近）",
    "area": "大洼区",
    "latitude": 40.735,
    "longitude": 121.935,
    "type": "泥滩",
    "harvest": "蛤蜊 · 小螃蟹",
    "terrainSafety": 11,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "jinzhou-bijiashan",
    "cityId": "jinzhou",
    "cityName": "锦州",
    "name": "笔架山海滨（附近）",
    "area": "太和区",
    "latitude": 40.823,
    "longitude": 121.073,
    "type": "礁石 + 滩涂",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 12,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "jinzhou-bay",
    "cityId": "jinzhou",
    "cityName": "锦州",
    "name": "锦州湾海滨浴场（附近）",
    "area": "太和区",
    "latitude": 40.806,
    "longitude": 121.132,
    "type": "沙滩",
    "harvest": "蛤蜊 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "huludao-xingcheng",
    "cityId": "huludao",
    "cityName": "葫芦岛",
    "name": "兴城海滨浴场（附近）",
    "area": "兴城市",
    "latitude": 40.616,
    "longitude": 120.754,
    "type": "沙滩",
    "harvest": "蛤蜊 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "huludao-longhuitou",
    "cityId": "huludao",
    "cityName": "葫芦岛",
    "name": "龙回头海滨岸段（附近）",
    "area": "兴城市",
    "latitude": 40.65,
    "longitude": 120.839,
    "type": "礁石 + 沙滩",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 14,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "qinhuangdao-geziwo",
    "cityId": "qinhuangdao",
    "cityName": "秦皇岛",
    "name": "鸽子窝公园海岸（附近）",
    "area": "北戴河区",
    "latitude": 39.825,
    "longitude": 119.531,
    "type": "礁石 + 沙滩",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 14,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "qinhuangdao-nandaihe",
    "cityId": "qinhuangdao",
    "cityName": "秦皇岛",
    "name": "南戴河海滨浴场（附近）",
    "area": "北戴河新区",
    "latitude": 39.785,
    "longitude": 119.432,
    "type": "沙滩",
    "harvest": "蛤蜊 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "tangshan-xiangyun",
    "cityId": "tangshan",
    "cityName": "唐山",
    "name": "祥云湾海滨温泉度假区（附近）",
    "area": "曹妃甸区",
    "latitude": 39.185,
    "longitude": 118.981,
    "type": "沙滩",
    "harvest": "蛤蜊 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "tangshan-putidao",
    "cityId": "tangshan",
    "cityName": "唐山",
    "name": "菩提岛湿地岸段（附近）",
    "area": "乐亭县",
    "latitude": 39.116,
    "longitude": 118.851,
    "type": "海岛湿地",
    "harvest": "仅观察，不采集",
    "terrainSafety": 8,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "cangzhou-nandagang",
    "cityId": "cangzhou",
    "cityName": "沧州",
    "name": "南大港湿地（附近）",
    "area": "黄骅市",
    "latitude": 38.502,
    "longitude": 117.527,
    "type": "滨海湿地",
    "harvest": "仅观察，不采集",
    "terrainSafety": 8,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "cangzhou-bohai",
    "cityId": "cangzhou",
    "cityName": "沧州",
    "name": "渤海新区滨海岸段（附近）",
    "area": "黄骅市",
    "latitude": 38.32,
    "longitude": 117.891,
    "type": "泥滩",
    "harvest": "蛤蜊 · 小螃蟹",
    "terrainSafety": 10,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "tianjin-dongjiang",
    "cityId": "tianjin",
    "cityName": "天津",
    "name": "东疆湾沙滩景区（附近）",
    "area": "滨海新区",
    "latitude": 39,
    "longitude": 117.802,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "tianjin-maritime",
    "cityId": "tianjin",
    "cityName": "天津",
    "name": "国家海洋博物馆滨海岸段（附近）",
    "area": "滨海新区",
    "latitude": 38.924,
    "longitude": 117.757,
    "type": "人工岸线 + 泥滩",
    "harvest": "仅观察，不采集",
    "terrainSafety": 9,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "lianyungang-liandao",
    "cityId": "lianyungang",
    "cityName": "连云港",
    "name": "连岛大沙湾（附近）",
    "area": "连云区",
    "latitude": 34.756,
    "longitude": 119.468,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "lianyungang-zaihai",
    "cityId": "lianyungang",
    "cityName": "连云港",
    "name": "在海一方公园岸段（附近）",
    "area": "连云区",
    "latitude": 34.751,
    "longitude": 119.393,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "yancheng-tiaozini",
    "cityId": "yancheng",
    "cityName": "盐城",
    "name": "条子泥湿地（附近）",
    "area": "东台市",
    "latitude": 32.758,
    "longitude": 120.903,
    "type": "滨海湿地",
    "harvest": "仅观察，不采集",
    "terrainSafety": 8,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "yancheng-sheyang",
    "cityId": "yancheng",
    "cityName": "盐城",
    "name": "射阳河口滨海岸段（附近）",
    "area": "射阳县",
    "latitude": 33.839,
    "longitude": 120.493,
    "type": "河口泥滩",
    "harvest": "蛤蜊 · 蛏子",
    "terrainSafety": 10,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "nantong-golden",
    "cityId": "nantong",
    "cityName": "南通",
    "name": "启东黄金海滩（附近）",
    "area": "启东市",
    "latitude": 31.709,
    "longitude": 121.984,
    "type": "泥沙滩",
    "harvest": "蛤蜊 · 蛏子",
    "terrainSafety": 14,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "nantong-yuantuojiao",
    "cityId": "nantong",
    "cityName": "南通",
    "name": "圆陀角滨海岸段（附近）",
    "area": "启东市",
    "latitude": 31.728,
    "longitude": 121.899,
    "type": "河口沙滩",
    "harvest": "蛤蜊 · 小螃蟹",
    "terrainSafety": 13,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "shanghai-fengxian",
    "cityId": "shanghai",
    "cityName": "上海",
    "name": "碧海金沙水上乐园（附近）",
    "area": "奉贤区",
    "latitude": 30.82,
    "longitude": 121.518,
    "type": "人工沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "shanghai-jinshan",
    "cityId": "shanghai",
    "cityName": "上海",
    "name": "金山城市沙滩（附近）",
    "area": "金山区",
    "latitude": 30.724,
    "longitude": 121.35,
    "type": "人工沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "shanghai-nanhui",
    "cityId": "shanghai",
    "cityName": "上海",
    "name": "南汇嘴观海公园（附近）",
    "area": "浦东新区",
    "latitude": 30.866,
    "longitude": 121.947,
    "type": "滨海湿地",
    "harvest": "仅观察，不采集",
    "terrainSafety": 8,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "jiaxing-jiulongshan",
    "cityId": "jiaxing",
    "cityName": "嘉兴",
    "name": "九龙山滨海岸段（附近）",
    "area": "平湖市",
    "latitude": 30.591,
    "longitude": 121.122,
    "type": "礁石 + 沙滩",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 13,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "jiaxing-guanhaiyuan",
    "cityId": "jiaxing",
    "cityName": "嘉兴",
    "name": "海盐观海园岸段（附近）",
    "area": "海盐县",
    "latitude": 30.542,
    "longitude": 120.998,
    "type": "人工岸线 + 泥滩",
    "harvest": "仅观察，不采集",
    "terrainSafety": 9,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "ningbo-songlanshan",
    "cityId": "ningbo",
    "cityName": "宁波",
    "name": "松兰山海滨浴场（附近）",
    "area": "象山县",
    "latitude": 29.509,
    "longitude": 121.919,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "ningbo-banbianshan",
    "cityId": "ningbo",
    "cityName": "宁波",
    "name": "半边山沙滩（附近）",
    "area": "象山县",
    "latitude": 29.186,
    "longitude": 121.95,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "zhoushan-nansha",
    "cityId": "zhoushan",
    "cityName": "舟山",
    "name": "朱家尖南沙（附近）",
    "area": "普陀区",
    "latitude": 29.882,
    "longitude": 122.389,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "zhoushan-dongsha",
    "cityId": "zhoushan",
    "cityName": "舟山",
    "name": "朱家尖东沙（附近）",
    "area": "普陀区",
    "latitude": 29.899,
    "longitude": 122.396,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "zhoushan-jihu",
    "cityId": "zhoushan",
    "cityName": "舟山",
    "name": "嵊泗基湖沙滩（附近）",
    "area": "嵊泗县",
    "latitude": 30.727,
    "longitude": 122.45,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "taizhou-dongxia",
    "cityId": "taizhou-zj",
    "cityName": "台州",
    "name": "洞下沙滩（附近）",
    "area": "温岭市",
    "latitude": 28.383,
    "longitude": 121.619,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "taizhou-dachen",
    "cityId": "taizhou-zj",
    "cityName": "台州",
    "name": "大陈岛海滨岸段（附近）",
    "area": "椒江区",
    "latitude": 28.451,
    "longitude": 121.899,
    "type": "礁石 + 沙滩",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 13,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "wenzhou-banping",
    "cityId": "wenzhou",
    "cityName": "温州",
    "name": "洞头半屏山海岸（附近）",
    "area": "洞头区",
    "latitude": 27.84,
    "longitude": 121.171,
    "type": "礁石 + 沙滩",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 13,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "wenzhou-nanji",
    "cityId": "wenzhou",
    "cityName": "温州",
    "name": "南麂岛大沙岙（附近）",
    "area": "平阳县",
    "latitude": 27.46,
    "longitude": 121.052,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "ningde-beiqi",
    "cityId": "ningde",
    "cityName": "宁德",
    "name": "霞浦北岐滩涂（附近）",
    "area": "霞浦县",
    "latitude": 26.885,
    "longitude": 120.018,
    "type": "滩涂",
    "harvest": "仅观察，不采集",
    "terrainSafety": 9,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "ningde-dongbi",
    "cityId": "ningde",
    "cityName": "宁德",
    "name": "霞浦东壁海岸（附近）",
    "area": "霞浦县",
    "latitude": 26.884,
    "longitude": 120.139,
    "type": "礁石 + 滩涂",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 12,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "fuzhou-longwangtou",
    "cityId": "fuzhou",
    "cityName": "福州",
    "name": "平潭龙王头沙滩（附近）",
    "area": "平潭县",
    "latitude": 25.504,
    "longitude": 119.799,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "fuzhou-xiasha",
    "cityId": "fuzhou",
    "cityName": "福州",
    "name": "长乐下沙海滩（附近）",
    "area": "长乐区",
    "latitude": 25.879,
    "longitude": 119.665,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "putian-meizhou",
    "cityId": "putian",
    "cityName": "莆田",
    "name": "湄洲岛黄金沙滩（附近）",
    "area": "秀屿区",
    "latitude": 25.083,
    "longitude": 119.128,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "putian-rinan",
    "cityId": "putian",
    "cityName": "莆田",
    "name": "南日岛海滨岸段（附近）",
    "area": "秀屿区",
    "latitude": 25.203,
    "longitude": 119.228,
    "type": "礁石 + 沙滩",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 14,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "quanzhou-chongwu",
    "cityId": "quanzhou",
    "cityName": "泉州",
    "name": "崇武古城海岸（附近）",
    "area": "惠安县",
    "latitude": 24.888,
    "longitude": 118.921,
    "type": "礁石 + 沙滩",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 14,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "quanzhou-goldcoast",
    "cityId": "quanzhou",
    "cityName": "泉州",
    "name": "石狮黄金海岸（附近）",
    "area": "石狮市",
    "latitude": 24.73,
    "longitude": 118.688,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "xiamen-huangcuo",
    "cityId": "xiamen",
    "cityName": "厦门",
    "name": "黄厝海滩（附近）",
    "area": "思明区",
    "latitude": 24.438,
    "longitude": 118.151,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "xiamen-wuyuan",
    "cityId": "xiamen",
    "cityName": "厦门",
    "name": "五缘湾沙滩（附近）",
    "area": "湖里区",
    "latitude": 24.532,
    "longitude": 118.171,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "zhangzhou-maluan",
    "cityId": "zhangzhou",
    "cityName": "漳州",
    "name": "东山马銮湾（附近）",
    "area": "东山县",
    "latitude": 23.719,
    "longitude": 117.52,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "zhangzhou-liuao",
    "cityId": "zhangzhou",
    "cityName": "漳州",
    "name": "六鳌翡翠湾（附近）",
    "area": "漳浦县",
    "latitude": 23.978,
    "longitude": 117.744,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "chaozhou-greenisland",
    "cityId": "chaozhou",
    "cityName": "潮州",
    "name": "饶平绿岛旅游山庄海岸（附近）",
    "area": "饶平县",
    "latitude": 23.617,
    "longitude": 117.102,
    "type": "礁石 + 沙滩",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 13,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "chaozhou-xunzhou",
    "cityId": "chaozhou",
    "cityName": "潮州",
    "name": "汛洲岛海滨岸段（附近）",
    "area": "饶平县",
    "latitude": 23.6,
    "longitude": 116.995,
    "type": "海岛滩涂",
    "harvest": "蛤蜊 · 小螃蟹",
    "terrainSafety": 12,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "shantou-qingao",
    "cityId": "shantou",
    "cityName": "汕头",
    "name": "南澳青澳湾（附近）",
    "area": "南澳县",
    "latitude": 23.429,
    "longitude": 117.133,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "shantou-zhongxin",
    "cityId": "shantou",
    "cityName": "汕头",
    "name": "中信滨海沙滩（附近）",
    "area": "濠江区",
    "latitude": 23.268,
    "longitude": 116.751,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "jieyang-huilai",
    "cityId": "jieyang",
    "cityName": "揭阳",
    "name": "惠来滨海旅游度假区（附近）",
    "area": "惠来县",
    "latitude": 22.988,
    "longitude": 116.31,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "jieyang-keweiyi",
    "cityId": "jieyang",
    "cityName": "揭阳",
    "name": "客鸟尾石笋岸段（附近）",
    "area": "惠来县",
    "latitude": 22.953,
    "longitude": 116.491,
    "type": "礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 12,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "shanwei-redbay",
    "cityId": "shanwei",
    "cityName": "汕尾",
    "name": "红海湾遮浪海滩（附近）",
    "area": "城区",
    "latitude": 22.668,
    "longitude": 115.562,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "shanwei-jinding",
    "cityId": "shanwei",
    "cityName": "汕尾",
    "name": "金町湾沙滩（附近）",
    "area": "城区",
    "latitude": 22.792,
    "longitude": 115.305,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "huizhou-shuangyue",
    "cityId": "huizhou",
    "cityName": "惠州",
    "name": "双月湾沙滩（附近）",
    "area": "惠东县",
    "latitude": 22.563,
    "longitude": 114.894,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "huizhou-xunliao",
    "cityId": "huizhou",
    "cityName": "惠州",
    "name": "巽寮湾沙滩（附近）",
    "area": "惠东县",
    "latitude": 22.7,
    "longitude": 114.739,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "shenzhen-dameisha",
    "cityId": "shenzhen",
    "cityName": "深圳",
    "name": "大梅沙海滨公园（附近）",
    "area": "盐田区",
    "latitude": 22.596,
    "longitude": 114.306,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "shenzhen-xichong",
    "cityId": "shenzhen",
    "cityName": "深圳",
    "name": "西涌海滩（附近）",
    "area": "大鹏新区",
    "latitude": 22.481,
    "longitude": 114.545,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "dongguan-weiyuan",
    "cityId": "dongguan",
    "cityName": "东莞",
    "name": "威远岛滨海岸段（附近）",
    "area": "虎门镇",
    "latitude": 22.807,
    "longitude": 113.619,
    "type": "珠江口岸线",
    "harvest": "仅观察，不采集",
    "terrainSafety": 9,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "dongguan-shajiao",
    "cityId": "dongguan",
    "cityName": "东莞",
    "name": "沙角炮台滨江岸段（附近）",
    "area": "虎门镇",
    "latitude": 22.755,
    "longitude": 113.67,
    "type": "珠江口岸线",
    "harvest": "仅观察，不采集",
    "terrainSafety": 9,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "guangzhou-nansha",
    "cityId": "guangzhou",
    "cityName": "广州",
    "name": "南沙天后宫滨海岸段（附近）",
    "area": "南沙区",
    "latitude": 22.755,
    "longitude": 113.61,
    "type": "河口沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 12,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "guangzhou-wetland",
    "cityId": "guangzhou",
    "cityName": "广州",
    "name": "南沙湿地公园（附近）",
    "area": "南沙区",
    "latitude": 22.618,
    "longitude": 113.632,
    "type": "河口湿地",
    "harvest": "仅观察，不采集",
    "terrainSafety": 8,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "zhongshan-yakou",
    "cityId": "zhongshan",
    "cityName": "中山",
    "name": "崖口滨海岸段（附近）",
    "area": "南朗街道",
    "latitude": 22.499,
    "longitude": 113.573,
    "type": "河口滩涂",
    "harvest": "蛤蜊 · 小螃蟹",
    "terrainSafety": 10,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "zhongshan-cuiheng",
    "cityId": "zhongshan",
    "cityName": "中山",
    "name": "翠亨湿地岸段（附近）",
    "area": "翠亨新区",
    "latitude": 22.449,
    "longitude": 113.557,
    "type": "河口湿地",
    "harvest": "仅观察，不采集",
    "terrainSafety": 8,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "zhuhai-xianglu",
    "cityId": "zhuhai",
    "cityName": "珠海",
    "name": "香炉湾沙滩（附近）",
    "area": "香洲区",
    "latitude": 22.27,
    "longitude": 113.591,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "zhuhai-dongao",
    "cityId": "zhuhai",
    "cityName": "珠海",
    "name": "东澳岛南沙湾（附近）",
    "area": "香洲区",
    "latitude": 22.017,
    "longitude": 113.709,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "jiangmen-naqin",
    "cityId": "jiangmen",
    "cityName": "江门",
    "name": "那琴半岛海岸（附近）",
    "area": "台山市",
    "latitude": 21.817,
    "longitude": 112.581,
    "type": "礁石 + 沙滩",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 14,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "jiangmen-wangfuzhou",
    "cityId": "jiangmen",
    "cityName": "江门",
    "name": "下川岛王府洲（附近）",
    "area": "台山市",
    "latitude": 21.617,
    "longitude": 112.574,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "yangjiang-dajiaowan",
    "cityId": "yangjiang",
    "cityName": "阳江",
    "name": "海陵岛大角湾（附近）",
    "area": "江城区",
    "latitude": 21.572,
    "longitude": 111.852,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "yangjiang-shili",
    "cityId": "yangjiang",
    "cityName": "阳江",
    "name": "十里银滩（附近）",
    "area": "江城区",
    "latitude": 21.603,
    "longitude": 111.91,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "maoming-firstbeach",
    "cityId": "maoming",
    "cityName": "茂名",
    "name": "中国第一滩（附近）",
    "area": "电白区",
    "latitude": 21.468,
    "longitude": 111.043,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "maoming-fangji",
    "cityId": "maoming",
    "cityName": "茂名",
    "name": "放鸡岛海岸（附近）",
    "area": "电白区",
    "latitude": 21.39,
    "longitude": 111.213,
    "type": "礁石 + 沙滩",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 14,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "zhanjiang-jinshawan",
    "cityId": "zhanjiang",
    "cityName": "湛江",
    "name": "金沙湾海滨浴场（附近）",
    "area": "赤坎区",
    "latitude": 21.272,
    "longitude": 110.398,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "zhanjiang-techeng",
    "cityId": "zhanjiang",
    "cityName": "湛江",
    "name": "特呈岛海滨岸段（附近）",
    "area": "霞山区",
    "latitude": 21.151,
    "longitude": 110.438,
    "type": "红树林 + 沙滩",
    "harvest": "仅观察，不采集",
    "terrainSafety": 9,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "beihai-silver",
    "cityId": "beihai",
    "cityName": "北海",
    "name": "北海银滩（附近）",
    "area": "银海区",
    "latitude": 21.405,
    "longitude": 109.173,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "beihai-qiaogang",
    "cityId": "beihai",
    "cityName": "北海",
    "name": "侨港海滩（附近）",
    "area": "银海区",
    "latitude": 21.421,
    "longitude": 109.119,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "qinzhou-sanniang",
    "cityId": "qinzhou",
    "cityName": "钦州",
    "name": "三娘湾海滩（附近）",
    "area": "钦南区",
    "latitude": 21.608,
    "longitude": 108.755,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "qinzhou-maoweihai",
    "cityId": "qinzhou",
    "cityName": "钦州",
    "name": "茅尾海湿地岸段（附近）",
    "area": "钦南区",
    "latitude": 21.829,
    "longitude": 108.574,
    "type": "红树林湿地",
    "harvest": "仅观察，不采集",
    "terrainSafety": 8,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "fangcheng-bailang",
    "cityId": "fangchenggang",
    "cityName": "防城港",
    "name": "白浪滩（附近）",
    "area": "防城区",
    "latitude": 21.584,
    "longitude": 108.222,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "fangcheng-wanwei",
    "cityId": "fangchenggang",
    "cityName": "防城港",
    "name": "万尾金滩（附近）",
    "area": "东兴市",
    "latitude": 21.552,
    "longitude": 108.034,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "haikou-holiday",
    "cityId": "haikou",
    "cityName": "海口",
    "name": "假日海滩（附近）",
    "area": "秀英区",
    "latitude": 20.041,
    "longitude": 110.198,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "haikou-xixiu",
    "cityId": "haikou",
    "cityName": "海口",
    "name": "西秀海滩（附近）",
    "area": "秀英区",
    "latitude": 20.024,
    "longitude": 110.243,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "wenchang-moonbay",
    "cityId": "wenchang",
    "cityName": "文昌",
    "name": "月亮湾海滩（附近）",
    "area": "文昌市",
    "latitude": 19.65,
    "longitude": 111.036,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "wenchang-gaolong",
    "cityId": "wenchang",
    "cityName": "文昌",
    "name": "高隆湾海滩（附近）",
    "area": "文昌市",
    "latitude": 19.54,
    "longitude": 110.82,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "qionghai-boao",
    "cityId": "qionghai",
    "cityName": "琼海",
    "name": "博鳌海滨岸段（附近）",
    "area": "琼海市",
    "latitude": 19.159,
    "longitude": 110.582,
    "type": "河口沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 14,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "qionghai-tanmen",
    "cityId": "qionghai",
    "cityName": "琼海",
    "name": "潭门港外侧海滩（附近）",
    "area": "琼海市",
    "latitude": 19.241,
    "longitude": 110.687,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 14,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "wanning-riyue",
    "cityId": "wanning",
    "cityName": "万宁",
    "name": "日月湾海滩（附近）",
    "area": "万宁市",
    "latitude": 18.681,
    "longitude": 110.274,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "wanning-shimei",
    "cityId": "wanning",
    "cityName": "万宁",
    "name": "石梅湾海滩（附近）",
    "area": "万宁市",
    "latitude": 18.662,
    "longitude": 110.29,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "lingshui-qingshui",
    "cityId": "lingshui",
    "cityName": "陵水",
    "name": "清水湾沙滩（附近）",
    "area": "陵水县",
    "latitude": 18.404,
    "longitude": 109.96,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "lingshui-xiangshui",
    "cityId": "lingshui",
    "cityName": "陵水",
    "name": "香水湾海滩（附近）",
    "area": "陵水县",
    "latitude": 18.459,
    "longitude": 110.035,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "sanya-yalong",
    "cityId": "sanya",
    "cityName": "三亚",
    "name": "亚龙湾海滩（附近）",
    "area": "吉阳区",
    "latitude": 18.23,
    "longitude": 109.641,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "sanya-dadonghai",
    "cityId": "sanya",
    "cityName": "三亚",
    "name": "大东海海滩（附近）",
    "area": "吉阳区",
    "latitude": 18.22,
    "longitude": 109.522,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "ledong-longmu",
    "cityId": "ledong",
    "cityName": "乐东",
    "name": "龙沐湾海滩（附近）",
    "area": "乐东县",
    "latitude": 18.69,
    "longitude": 108.731,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "ledong-yinggehai",
    "cityId": "ledong",
    "cityName": "乐东",
    "name": "莺歌海海滨岸段（附近）",
    "area": "乐东县",
    "latitude": 18.509,
    "longitude": 108.704,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "dongfang-yulinzhou",
    "cityId": "dongfang",
    "cityName": "东方",
    "name": "鱼鳞洲海滩（附近）",
    "area": "东方市",
    "latitude": 19.102,
    "longitude": 108.621,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "dongfang-haidongfang",
    "cityId": "dongfang",
    "cityName": "东方",
    "name": "海东方沙滩（附近）",
    "area": "东方市",
    "latitude": 19,
    "longitude": 108.65,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "danzhou-haihua",
    "cityId": "danzhou",
    "cityName": "儋州",
    "name": "海花岛海滨岸段（附近）",
    "area": "儋州市",
    "latitude": 19.704,
    "longitude": 109.207,
    "type": "人工沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 15,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "danzhou-eman",
    "cityId": "danzhou",
    "cityName": "儋州",
    "name": "峨蔓火山海岸（附近）",
    "area": "儋州市",
    "latitude": 19.842,
    "longitude": 109.183,
    "type": "火山礁石岸",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 12,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "lingao-jiefang",
    "cityId": "lingao",
    "cityName": "临高",
    "name": "临高角解放公园海岸（附近）",
    "area": "临高县",
    "latitude": 19.997,
    "longitude": 109.714,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 14,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "lingao-golden",
    "cityId": "lingao",
    "cityName": "临高",
    "name": "金沙滩海滨岸段（附近）",
    "area": "临高县",
    "latitude": 19.913,
    "longitude": 109.689,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 16,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "chengmai-yingbin",
    "cityId": "chengmai",
    "cityName": "澄迈",
    "name": "盈滨半岛海滩（附近）",
    "area": "澄迈县",
    "latitude": 19.945,
    "longitude": 110.033,
    "type": "沙滩",
    "harvest": "贝类 · 小螃蟹",
    "terrainSafety": 17,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  },
  {
    "id": "chengmai-yubao",
    "cityId": "chengmai",
    "cityName": "澄迈",
    "name": "玉包港海滨岸段（附近）",
    "area": "澄迈县",
    "latitude": 19.891,
    "longitude": 109.951,
    "type": "沙滩 + 礁石",
    "harvest": "海螺 · 小螃蟹",
    "terrainSafety": 14,
    "verification": "公开资料待复核",
    "entry": "附近导航参考点，具体入口以现场公开通道为准",
    "shoreline": "仅限现场允许进入的退潮近岸区域",
    "direction": "到达后核对开放、收费、保护区和港区边界，不翻越围挡",
    "retreat": "遇封闭、红旗、保护提示或明显回涨立即停止并返回固定岸线"
  }
]

module.exports = { nationalCities, nationalSpots }
